name: Explosion Man
main: com.gmail.bunnehrealm.explosionman.MainClass
version: 1.3
description: >
            Explosion Man Commands!
commands:
  explode:
    description: Creates an Explosion! Usage - /explode [Power]
  fexplode:
    description: Creates an Explosion where you are looking! Usage - /fexplode [power]
  launch:
    description: Creates an explosion and shoots you in the air! Usage - /launch [power]